# Generated by Django 3.2.19 on 2023-06-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('idFacultad', models.AutoField(primary_key=True, serialize=False)),
                ('facultad', models.CharField(max_length=100)),
                ('femenino', models.IntegerField()),
                ('masculino', models.IntegerField()),
            ],
        ),
    ]
