# Generated by Django 3.2.19 on 2023-06-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('idDiscapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('discapacidad', models.CharField(max_length=100)),
                ('femenino', models.IntegerField()),
                ('masculino', models.IntegerField()),
            ],
        ),
    ]
