# Generated by Django 3.2.19 on 2023-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_tipodiscapacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='anio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodiscapacidad',
            name='anio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
